// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "termsOfService": "http://swagger.io/terms/",
        "contact": {
            "name": "Support",
            "email": "support@simas.id"
        },
        "license": {
            "name": "Apache 2.0",
            "url": "http://www.apache.org/licenses/LICENSE-2.0.html"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/api/v1/auth/mobile/login": {
            "post": {
                "description": "Login with email and password for mobile users.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Mobile Auth"
                ],
                "summary": "Mobile user login",
                "parameters": [
                    {
                        "description": "Login request",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/model.MobileLoginRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/model.SessionResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/model.ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/model.ErrorResponse"
                        }
                    },
                    "403": {
                        "description": "Forbidden",
                        "schema": {
                            "$ref": "#/definitions/model.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/model.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/v1/auth/mobile/oauth": {
            "post": {
                "description": "Authenticate mobile user using Google token. Returns session or pending state if new user.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Mobile Auth"
                ],
                "summary": "Google OAuth login for mobile",
                "parameters": [
                    {
                        "description": "Google OAuth request",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/model.MobileOAuthRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/model.SessionResponse"
                        }
                    },
                    "202": {
                        "description": "Accepted",
                        "schema": {
                            "$ref": "#/definitions/model.OAuthPendingResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/model.ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/model.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/v1/auth/mobile/oauth/complete": {
            "post": {
                "description": "Complete Google OAuth registration for mobile by providing temp_user_id and WhatsApp number.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Mobile Auth"
                ],
                "summary": "Complete mobile OAuth registration",
                "parameters": [
                    {
                        "description": "Complete OAuth request",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/model.CompleteOAuthRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/model.SessionResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/model.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/model.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/v1/auth/mobile/register": {
            "post": {
                "description": "Register a new user with email, WhatsApp, and password. An OTP will be sent to the email.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Mobile Auth"
                ],
                "summary": "Register new mobile user",
                "parameters": [
                    {
                        "description": "Registration request",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/model.RegisterRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/model.RegisterResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/model.ErrorResponse"
                        }
                    },
                    "409": {
                        "description": "Conflict",
                        "schema": {
                            "$ref": "#/definitions/model.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/model.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/v1/auth/mobile/resend-otp": {
            "post": {
                "description": "Resend OTP code to the user's email.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Mobile Auth"
                ],
                "summary": "Resend OTP code",
                "parameters": [
                    {
                        "description": "Resend OTP request",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/model.ResendOTPRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/model.ResendResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/model.ErrorResponse"
                        }
                    },
                    "429": {
                        "description": "Too Many Requests",
                        "schema": {
                            "$ref": "#/definitions/model.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/v1/auth/mobile/verify-otp": {
            "post": {
                "description": "Verify the OTP code sent to the user's email during registration.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Mobile Auth"
                ],
                "summary": "Verify OTP code",
                "parameters": [
                    {
                        "description": "OTP verification request",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/model.VerifyOTPRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/model.SessionResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/model.ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/model.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/v1/auth/refresh": {
            "post": {
                "description": "Refresh access token using a valid refresh token.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Mobile Auth"
                ],
                "summary": "Refresh access token",
                "parameters": [
                    {
                        "description": "Refresh token request",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/model.RefreshRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/model.SessionResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/model.ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/model.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/v1/mobile/status-verifikasi": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Returns the verification and account status for the authenticated mobile user.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Mobile"
                ],
                "summary": "Get mobile user verification status",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/model.StatusVerifikasiResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/model.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/v1/sekolah": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "List semua sekolah dengan filter status, search, dan pagination. Super Admin only.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Sekolah"
                ],
                "summary": "List sekolah dengan filter",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Filter status: pengajuan, menunggu_verifikasi, aktif, nonaktif, ditolak",
                        "name": "status",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Search nama atau NPSN",
                        "name": "search",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "default": 1,
                        "description": "Page number",
                        "name": "page",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "default": 20,
                        "description": "Items per page",
                        "name": "limit",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "{data[], total, page, limit}",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/model.ErrorResponse"
                        }
                    },
                    "403": {
                        "description": "Forbidden",
                        "schema": {
                            "$ref": "#/definitions/model.ErrorResponse"
                        }
                    }
                }
            },
            "post": {
                "description": "Submit data sekolah tanpa file. Response mengembalikan sekolah_id dan tracking_code. Step 2: upload dokumen via POST /sekolah/:id/dokumen",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Sekolah"
                ],
                "summary": "Step 1: Pengajuan baru sekolah (data saja)",
                "parameters": [
                    {
                        "description": "Data sekolah",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/model.SekolahRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "{id, tracking_code, status}",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/model.ErrorResponse"
                        }
                    },
                    "409": {
                        "description": "Conflict",
                        "schema": {
                            "$ref": "#/definitions/model.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/v1/sekolah/jenjang": {
            "get": {
                "description": "Public endpoint untuk mendapatkan daftar jenjang pendidikan.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Sekolah"
                ],
                "summary": "List jenjang pendidikan (master data)",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "type": "object",
                                "additionalProperties": {
                                    "type": "string"
                                }
                            }
                        }
                    }
                }
            }
        },
        "/api/v1/sekolah/lengkap": {
            "post": {
                "description": "Submit data sekolah + 4 file PDF legalitas via multipart/form-data. Status langsung \"menunggu_verifikasi\". Field data sama dengan SekolahRequest, file: akta_pendirian, nib, sk_pendirian, siop.",
                "consumes": [
                    "multipart/form-data"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Sekolah"
                ],
                "summary": "Pengajuan baru sekolah dengan data + dokumen legalitas sekaligus",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Nama sekolah",
                        "name": "nama",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "enum": [
                            "sd_mi",
                            "smp_mts",
                            "sma_smk_ma_mak"
                        ],
                        "type": "string",
                        "description": "Jenjang",
                        "name": "jenjang",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Email sekolah",
                        "name": "email",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "NPSN",
                        "name": "npsn",
                        "in": "formData"
                    },
                    {
                        "type": "string",
                        "description": "Alamat",
                        "name": "alamat",
                        "in": "formData"
                    },
                    {
                        "type": "integer",
                        "description": "Provinsi ID",
                        "name": "provinsi_id",
                        "in": "formData"
                    },
                    {
                        "type": "integer",
                        "description": "Kabupaten ID",
                        "name": "kabupaten_id",
                        "in": "formData"
                    },
                    {
                        "type": "integer",
                        "description": "Kecamatan ID",
                        "name": "kecamatan_id",
                        "in": "formData"
                    },
                    {
                        "type": "integer",
                        "description": "Desa ID",
                        "name": "desa_id",
                        "in": "formData"
                    },
                    {
                        "type": "string",
                        "description": "Kode pos",
                        "name": "kode_pos",
                        "in": "formData"
                    },
                    {
                        "type": "number",
                        "description": "Latitude",
                        "name": "latitude",
                        "in": "formData"
                    },
                    {
                        "type": "number",
                        "description": "Longitude",
                        "name": "longitude",
                        "in": "formData"
                    },
                    {
                        "type": "string",
                        "description": "Telepon",
                        "name": "telepon",
                        "in": "formData"
                    },
                    {
                        "type": "string",
                        "description": "Website",
                        "name": "website",
                        "in": "formData"
                    },
                    {
                        "type": "string",
                        "description": "Yayasan",
                        "name": "yayasan",
                        "in": "formData"
                    },
                    {
                        "type": "string",
                        "description": "Nama kepala sekolah",
                        "name": "kepala_sekolah_nama",
                        "in": "formData"
                    },
                    {
                        "type": "string",
                        "description": "NIP kepala sekolah",
                        "name": "kepala_sekolah_nip",
                        "in": "formData"
                    },
                    {
                        "type": "string",
                        "description": "YYYY-MM-DD",
                        "name": "tanggal_berdiri",
                        "in": "formData"
                    },
                    {
                        "type": "string",
                        "description": "Nomor SK pendirian",
                        "name": "sk_pendirian",
                        "in": "formData"
                    },
                    {
                        "type": "file",
                        "description": "Akta Pendirian (PDF, max 3MB)",
                        "name": "akta_pendirian",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "file",
                        "description": "NIB (PDF, max 3MB)",
                        "name": "nib",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "file",
                        "description": "SK Pendirian (PDF, max 3MB)",
                        "name": "sk_pendirian_file",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "file",
                        "description": "Surat Izin Operasional (PDF, max 3MB)",
                        "name": "siop",
                        "in": "formData",
                        "required": true
                    }
                ],
                "responses": {
                    "201": {
                        "description": "{id, tracking_code, status, status_label, message}",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/model.ErrorResponse"
                        }
                    },
                    "409": {
                        "description": "Conflict",
                        "schema": {
                            "$ref": "#/definitions/model.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/v1/sekolah/progress": {
            "get": {
                "description": "Cek status pengajuan sekolah menggunakan tracking_code. Tidak perlu autentikasi.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Sekolah"
                ],
                "summary": "Track progress pengajuan sekolah (public, no auth)",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Tracking code dari response pengajuan",
                        "name": "tracking_code",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/model.SekolahProgressResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/model.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/v1/sekolah/saya": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Admin Sekolah melihat data sekolahnya sendiri.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Sekolah"
                ],
                "summary": "Get data sekolah milik admin yang login",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/model.Sekolah"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/model.ErrorResponse"
                        }
                    }
                }
            },
            "put": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Admin Sekolah update data dasar sekolah (alamat, telepon, website, logo, koordinat).",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Sekolah"
                ],
                "summary": "Update data sekolah milik admin yang login",
                "parameters": [
                    {
                        "description": "Update request",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/model.SekolahUpdateRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/model.Sekolah"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/model.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/v1/sekolah/saya/pengajuan-ulang": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Admin Sekolah mengajukan ulang setelah status ditolak. Status kembali ke pengajuan, dokumen harus diupload ulang.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Sekolah"
                ],
                "summary": "Pengajuan ulang setelah ditolak",
                "parameters": [
                    {
                        "description": "Data sekolah baru",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/model.SekolahRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "{id, tracking_code, status}",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/model.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/v1/sekolah/{id}": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Detail sekolah dengan history state log. Super Admin only.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Sekolah"
                ],
                "summary": "Detail sekolah + state log",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Sekolah ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "{sekolah, state_logs}",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/model.ErrorResponse"
                        }
                    },
                    "403": {
                        "description": "Forbidden",
                        "schema": {
                            "$ref": "#/definitions/model.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/model.ErrorResponse"
                        }
                    }
                }
            },
            "put": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Update data sekolah. Super Admin only.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Sekolah"
                ],
                "summary": "Update data sekolah",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Sekolah ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Update request",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/model.SekolahUpdateRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/model.Sekolah"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/model.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/v1/sekolah/{id}/dokumen-legalitas": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Generate presigned URL untuk preview/download 4 dokumen legalitas. Super Admin only.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Sekolah"
                ],
                "summary": "Get presigned URL dokumen legalitas",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Sekolah ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/model.ErrorResponse"
                        }
                    },
                    "403": {
                        "description": "Forbidden",
                        "schema": {
                            "$ref": "#/definitions/model.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/v1/sekolah/{id}/verifikasi": {
            "put": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Super Admin setuju/tolak pengajuan sekolah. Setuju: status -\u003e aktif (auto-generate akun admin_sekolah). Tolak: status -\u003e ditolak.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Sekolah"
                ],
                "summary": "Verifikasi pengajuan sekolah",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Sekolah ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Verifikasi request",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/model.SekolahVerifikasiRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/model.Sekolah"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/model.ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/model.ErrorResponse"
                        }
                    },
                    "403": {
                        "description": "Forbidden",
                        "schema": {
                            "$ref": "#/definitions/model.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/v1/sekolah/{sekolah_id}/dokumen": {
            "post": {
                "description": "Upload 4 file PDF legalitas via multipart/form-data: akta_pendirian, nib, sk_pendirian, siop. Max 3MB per file. Status otomatis berubah ke \"menunggu_verifikasi\"",
                "consumes": [
                    "multipart/form-data"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Sekolah"
                ],
                "summary": "Step 2: Upload 4 dokumen legalitas (form-data)",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Sekolah ID dari step 1",
                        "name": "sekolah_id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "file",
                        "description": "Akta Pendirian Yayasan/Badan Hukum (PDF, max 3MB)",
                        "name": "akta_pendirian",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "file",
                        "description": "Nomor Induk Berusaha (PDF, max 3MB)",
                        "name": "nib",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "file",
                        "description": "SK Pendirian Sekolah (PDF, max 3MB)",
                        "name": "sk_pendirian",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "file",
                        "description": "Surat Izin Operasional (PDF, max 3MB)",
                        "name": "siop",
                        "in": "formData",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/model.Sekolah"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/model.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/model.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/auth/config": {
            "get": {
                "description": "Returns public authentication configuration including Google Client ID.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Auth"
                ],
                "summary": "Get public auth config",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/auth/google": {
            "post": {
                "description": "Authenticate user using Google ID token. Returns session or pending OAuth state.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Auth"
                ],
                "summary": "Google OAuth login (legacy endpoint)",
                "parameters": [
                    {
                        "description": "Google ID token",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/handler.LoginRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/model.SessionResponse"
                        }
                    },
                    "202": {
                        "description": "Accepted",
                        "schema": {
                            "$ref": "#/definitions/model.OAuthPendingResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/model.ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/model.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/model.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/auth/internal/login": {
            "post": {
                "description": "Login for internal users (staff, teachers, etc.).",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Internal Auth"
                ],
                "summary": "Internal user login",
                "parameters": [
                    {
                        "description": "Internal login request",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/handler.InternalLoginRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/model.SessionResponse"
                        }
                    },
                    "202": {
                        "description": "Accepted",
                        "schema": {
                            "$ref": "#/definitions/model.ForceUpdateResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/model.ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/model.ErrorResponse"
                        }
                    },
                    "403": {
                        "description": "Forbidden",
                        "schema": {
                            "$ref": "#/definitions/model.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/auth/internal/update-password": {
            "put": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Update password for internal user on first login or forced reset.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Internal Auth"
                ],
                "summary": "Force update internal user password",
                "parameters": [
                    {
                        "description": "Force update password request",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/handler.ForceUpdateRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/model.SessionResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/model.ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/model.ErrorResponse"
                        }
                    },
                    "403": {
                        "description": "Forbidden",
                        "schema": {
                            "$ref": "#/definitions/model.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/auth/logout": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Revoke access token and refresh token to logout user.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Auth"
                ],
                "summary": "Logout user",
                "parameters": [
                    {
                        "description": "Optional refresh token",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/model.RefreshRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/auth/me": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Returns the currently authenticated user profile.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Auth"
                ],
                "summary": "Get current authenticated user",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/model.User"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/model.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/auth/oauth/complete": {
            "post": {
                "description": "Complete OAuth registration by providing temp_user_id and WhatsApp number.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Auth"
                ],
                "summary": "Complete pending Google OAuth registration",
                "parameters": [
                    {
                        "description": "Complete OAuth request",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/model.CompleteOAuthRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/model.SessionResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/model.ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/model.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/model.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/auth/pusat/login": {
            "post": {
                "description": "Login for super admin / pusat accounts.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Internal Auth"
                ],
                "summary": "Pusat (Super Admin) login",
                "parameters": [
                    {
                        "description": "Pusat login request",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/handler.PusatLoginRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/model.SessionResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/model.ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/model.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/auth/pusat/register": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Register a new super admin account. Only accessible by existing super_admin.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Internal Auth"
                ],
                "summary": "Register new super admin",
                "parameters": [
                    {
                        "description": "Register super admin request",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/handler.RegisterSuperAdminRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/model.SessionResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/model.ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/model.ErrorResponse"
                        }
                    },
                    "403": {
                        "description": "Forbidden",
                        "schema": {
                            "$ref": "#/definitions/model.ErrorResponse"
                        }
                    },
                    "409": {
                        "description": "Conflict",
                        "schema": {
                            "$ref": "#/definitions/model.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/auth/refresh": {
            "post": {
                "description": "Refresh access token using a valid refresh token.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Auth"
                ],
                "summary": "Refresh access token",
                "parameters": [
                    {
                        "description": "Refresh token request",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/model.RefreshRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/model.SessionResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/model.ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/model.ErrorResponse"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "handler.ForceUpdateRequest": {
            "type": "object",
            "required": [
                "confirm_password",
                "new_password",
                "old_password"
            ],
            "properties": {
                "confirm_password": {
                    "type": "string",
                    "minLength": 8
                },
                "new_password": {
                    "type": "string",
                    "minLength": 8
                },
                "old_password": {
                    "type": "string"
                }
            }
        },
        "handler.InternalLoginRequest": {
            "type": "object",
            "required": [
                "email",
                "password"
            ],
            "properties": {
                "email": {
                    "type": "string"
                },
                "password": {
                    "type": "string"
                }
            }
        },
        "handler.LoginRequest": {
            "type": "object",
            "required": [
                "id_token"
            ],
            "properties": {
                "id_token": {
                    "type": "string"
                }
            }
        },
        "handler.PusatLoginRequest": {
            "type": "object",
            "required": [
                "email",
                "password"
            ],
            "properties": {
                "email": {
                    "type": "string"
                },
                "password": {
                    "type": "string"
                }
            }
        },
        "handler.RegisterSuperAdminRequest": {
            "type": "object",
            "required": [
                "email",
                "name",
                "password"
            ],
            "properties": {
                "email": {
                    "type": "string"
                },
                "name": {
                    "type": "string",
                    "maxLength": 255,
                    "minLength": 3
                },
                "password": {
                    "type": "string",
                    "minLength": 8
                }
            }
        },
        "model.CompleteOAuthRequest": {
            "type": "object",
            "required": [
                "no_whatsapp",
                "temp_user_id"
            ],
            "properties": {
                "no_whatsapp": {
                    "type": "string",
                    "maxLength": 15,
                    "minLength": 9
                },
                "temp_user_id": {
                    "type": "string"
                }
            }
        },
        "model.ErrorResponse": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "string"
                },
                "message": {
                    "type": "string"
                }
            }
        },
        "model.ForceUpdateResponse": {
            "type": "object",
            "properties": {
                "account_state": {
                    "type": "string"
                },
                "expires_in": {
                    "type": "integer"
                },
                "temp_token": {
                    "type": "string"
                }
            }
        },
        "model.MobileLoginRequest": {
            "type": "object",
            "required": [
                "email",
                "password"
            ],
            "properties": {
                "email": {
                    "type": "string"
                },
                "password": {
                    "type": "string"
                }
            }
        },
        "model.MobileOAuthRequest": {
            "type": "object",
            "required": [
                "google_token"
            ],
            "properties": {
                "google_token": {
                    "type": "string"
                }
            }
        },
        "model.OAuthPendingResponse": {
            "type": "object",
            "properties": {
                "account_state": {
                    "type": "string"
                },
                "avatar_url": {
                    "type": "string"
                },
                "email": {
                    "type": "string"
                },
                "expires_in": {
                    "type": "integer"
                },
                "name": {
                    "type": "string"
                },
                "temp_user_id": {
                    "type": "string"
                }
            }
        },
        "model.RefreshRequest": {
            "type": "object",
            "required": [
                "refresh_token"
            ],
            "properties": {
                "refresh_token": {
                    "type": "string"
                }
            }
        },
        "model.RegisterRequest": {
            "type": "object",
            "required": [
                "email",
                "nama_lengkap",
                "no_whatsapp",
                "password"
            ],
            "properties": {
                "email": {
                    "type": "string"
                },
                "nama_lengkap": {
                    "type": "string",
                    "maxLength": 255,
                    "minLength": 3
                },
                "no_whatsapp": {
                    "type": "string",
                    "maxLength": 15,
                    "minLength": 9
                },
                "password": {
                    "type": "string",
                    "minLength": 8
                }
            }
        },
        "model.RegisterResponse": {
            "type": "object",
            "properties": {
                "email": {
                    "type": "string"
                },
                "expires_in": {
                    "type": "integer"
                },
                "message": {
                    "type": "string"
                }
            }
        },
        "model.ResendOTPRequest": {
            "type": "object",
            "required": [
                "email"
            ],
            "properties": {
                "email": {
                    "type": "string"
                }
            }
        },
        "model.ResendResponse": {
            "type": "object",
            "properties": {
                "expires_in": {
                    "type": "integer"
                },
                "message": {
                    "type": "string"
                }
            }
        },
        "model.Sekolah": {
            "type": "object",
            "properties": {
                "admin_sekolah_id": {
                    "type": "string"
                },
                "akta_pendirian_url": {
                    "type": "string"
                },
                "alamat": {
                    "type": "string"
                },
                "created_at": {
                    "type": "string"
                },
                "desa_id": {
                    "type": "integer"
                },
                "email": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "jenjang": {
                    "type": "string"
                },
                "jumlah_pendidik": {
                    "type": "integer"
                },
                "jumlah_siswa": {
                    "type": "integer"
                },
                "kabupaten_id": {
                    "type": "integer"
                },
                "kecamatan_id": {
                    "type": "integer"
                },
                "kepala_sekolah_nama": {
                    "type": "string"
                },
                "kepala_sekolah_nip": {
                    "type": "string"
                },
                "kode_pos": {
                    "type": "string"
                },
                "latitude": {
                    "type": "number"
                },
                "logo_url": {
                    "type": "string"
                },
                "longitude": {
                    "type": "number"
                },
                "nama": {
                    "type": "string"
                },
                "nib_url": {
                    "type": "string"
                },
                "npsn": {
                    "type": "string"
                },
                "provinsi_id": {
                    "type": "integer"
                },
                "siop_url": {
                    "type": "string"
                },
                "sk_pendirian": {
                    "type": "string"
                },
                "sk_pendirian_url": {
                    "type": "string"
                },
                "status": {
                    "type": "string"
                },
                "tanggal_berdiri": {
                    "type": "string"
                },
                "telepon": {
                    "type": "string"
                },
                "tracking_code": {
                    "type": "string"
                },
                "updated_at": {
                    "type": "string"
                },
                "website": {
                    "type": "string"
                },
                "yayasan": {
                    "type": "string"
                }
            }
        },
        "model.SekolahProgressResponse": {
            "type": "object",
            "properties": {
                "created_at": {
                    "type": "string"
                },
                "email": {
                    "type": "string"
                },
                "nama": {
                    "type": "string"
                },
                "state_logs": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/model.SekolahStateLogSummary"
                    }
                },
                "status": {
                    "type": "string"
                },
                "status_label": {
                    "type": "string"
                },
                "tracking_code": {
                    "type": "string"
                },
                "updated_at": {
                    "type": "string"
                }
            }
        },
        "model.SekolahRequest": {
            "type": "object",
            "required": [
                "email",
                "jenjang",
                "nama"
            ],
            "properties": {
                "alamat": {
                    "type": "string"
                },
                "desa_id": {
                    "type": "integer"
                },
                "email": {
                    "type": "string",
                    "maxLength": 255
                },
                "jenjang": {
                    "type": "string",
                    "enum": [
                        "sd_mi",
                        "smp_mts",
                        "sma_smk_ma_mak"
                    ]
                },
                "kabupaten_id": {
                    "type": "integer"
                },
                "kecamatan_id": {
                    "type": "integer"
                },
                "kepala_sekolah_nama": {
                    "type": "string"
                },
                "kepala_sekolah_nip": {
                    "type": "string"
                },
                "kode_pos": {
                    "type": "string"
                },
                "latitude": {
                    "type": "number"
                },
                "longitude": {
                    "type": "number"
                },
                "nama": {
                    "type": "string",
                    "maxLength": 255
                },
                "npsn": {
                    "type": "string"
                },
                "provinsi_id": {
                    "type": "integer"
                },
                "sk_pendirian": {
                    "type": "string"
                },
                "tanggal_berdiri": {
                    "type": "string"
                },
                "telepon": {
                    "type": "string"
                },
                "website": {
                    "type": "string"
                },
                "yayasan": {
                    "type": "string"
                }
            }
        },
        "model.SekolahStateLogSummary": {
            "type": "object",
            "properties": {
                "catatan": {
                    "type": "string"
                },
                "created_at": {
                    "type": "string"
                },
                "status_baru": {
                    "type": "string"
                },
                "status_label": {
                    "type": "string"
                }
            }
        },
        "model.SekolahUpdateRequest": {
            "type": "object",
            "properties": {
                "alamat": {
                    "type": "string"
                },
                "desa_id": {
                    "type": "integer"
                },
                "jenjang": {
                    "type": "string",
                    "enum": [
                        "sd_mi",
                        "smp_mts",
                        "sma_smk_ma_mak"
                    ]
                },
                "kabupaten_id": {
                    "type": "integer"
                },
                "kecamatan_id": {
                    "type": "integer"
                },
                "kepala_sekolah_nama": {
                    "type": "string"
                },
                "kepala_sekolah_nip": {
                    "type": "string"
                },
                "kode_pos": {
                    "type": "string"
                },
                "latitude": {
                    "type": "number"
                },
                "logo_url": {
                    "type": "string"
                },
                "longitude": {
                    "type": "number"
                },
                "nama": {
                    "type": "string"
                },
                "npsn": {
                    "type": "string"
                },
                "provinsi_id": {
                    "type": "integer"
                },
                "sk_pendirian": {
                    "type": "string"
                },
                "tanggal_berdiri": {
                    "type": "string"
                },
                "telepon": {
                    "type": "string"
                },
                "website": {
                    "type": "string"
                },
                "yayasan": {
                    "type": "string"
                }
            }
        },
        "model.SekolahVerifikasiRequest": {
            "type": "object",
            "required": [
                "status_baru"
            ],
            "properties": {
                "catatan": {
                    "type": "string"
                },
                "status_baru": {
                    "type": "string",
                    "enum": [
                        "menunggu_verifikasi",
                        "aktif",
                        "ditolak"
                    ]
                }
            }
        },
        "model.SessionResponse": {
            "type": "object",
            "properties": {
                "access_token": {
                    "type": "string"
                },
                "account_status": {
                    "type": "string"
                },
                "expires_in": {
                    "type": "integer"
                },
                "onboarding_status": {
                    "type": "string"
                },
                "refresh_token": {
                    "type": "string"
                },
                "user": {
                    "$ref": "#/definitions/model.User"
                }
            }
        },
        "model.StatusVerifikasiResponse": {
            "type": "object",
            "properties": {
                "account_status": {
                    "type": "string"
                },
                "status": {
                    "type": "string"
                }
            }
        },
        "model.User": {
            "type": "object",
            "properties": {
                "account_status": {
                    "type": "string"
                },
                "avatar_url": {
                    "type": "string"
                },
                "created_at": {
                    "type": "string"
                },
                "email": {
                    "type": "string"
                },
                "email_verified": {
                    "type": "boolean"
                },
                "email_verified_at": {
                    "type": "string"
                },
                "google_id": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "is_password_updated": {
                    "type": "boolean"
                },
                "last_login_at": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "no_whatsapp": {
                    "type": "string"
                },
                "onboarding_status": {
                    "type": "string"
                },
                "provider": {
                    "type": "string"
                },
                "role": {
                    "type": "string"
                },
                "updated_at": {
                    "type": "string"
                }
            }
        },
        "model.VerifyOTPRequest": {
            "type": "object",
            "required": [
                "email",
                "otp_code"
            ],
            "properties": {
                "email": {
                    "type": "string"
                },
                "otp_code": {
                    "type": "string"
                }
            }
        }
    },
    "securityDefinitions": {
        "BearerAuth": {
            "description": "Type \"Bearer\" followed by a space and JWT token.",
            "type": "apiKey",
            "name": "Authorization",
            "in": "header"
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:8080",
	BasePath:         "/",
	Schemes:          []string{},
	Title:            "SIMAS API",
	Description:      "API documentation for SIMAS (Sistem Informasi Manajemen Sekolah) backend.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
